package com.treineai.parity

import com.treineai.app.data.Exercise
import com.treineai.app.data.RepRange

val FIXTURES: List<Exercise> = listOf(
    Exercise(id="supino-reto", name="Supino reto", pattern="benchPress", view="lateral", rep=RepRange("elbow", 168.0, 78.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "lockout")),
    Exercise(id="supino-inclinado", name="Supino inclinado", pattern="benchPress", view="lateral", rep=RepRange("elbow", 166.0, 80.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="flexao-braco", name="Flexão de braço", pattern="pushup", view="lateral", rep=RepRange("elbow", 165.0, 82.0), hold=false, checks=listOf("rom", "tempo", "hipSag", "headPos")),
    Exercise(id="crucifixo", name="Crucifixo", pattern="fly", view="lateral", rep=RepRange("shoulder", 96.0, 24.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="flexao-inclinada", name="Flexão inclinada", pattern="pushup", view="lateral", rep=RepRange("elbow", 167.0, 88.0), hold=false, checks=listOf("rom", "tempo", "hipSag")),
    Exercise(id="crossover", name="Crossover na polia", pattern="fly", view="frontal", rep=RepRange("shoulder", 92.0, 20.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="remada-curvada", name="Remada curvada", pattern="row", view="lateral", rep=RepRange("elbow", 162.0, 68.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "backNeutral")),
    Exercise(id="puxada-frente", name="Puxada frontal", pattern="pulldown", view="frontal", rep=RepRange("elbow", 168.0, 62.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "torsoStable")),
    Exercise(id="barra-fixa", name="Barra fixa", pattern="pullup", view="frontal", rep=RepRange("elbow", 170.0, 55.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "momentum")),
    Exercise(id="remada-unilateral", name="Remada unilateral", pattern="row", view="lateral", rep=RepRange("elbow", 165.0, 65.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "backNeutral")),
    Exercise(id="remada-baixa", name="Remada baixa", pattern="row", view="lateral", rep=RepRange("elbow", 166.0, 66.0), hold=false, checks=listOf("rom", "tempo", "torsoStable")),
    Exercise(id="pulldown-reto", name="Pullover na polia", pattern="frontRaise", view="lateral", rep=RepRange("shoulder", 150.0, 40.0), hold=false, checks=listOf("rom", "tempo", "torsoStable")),
    Exercise(id="desenvolvimento", name="Desenvolvimento militar", pattern="overheadPress", view="frontal", rep=RepRange("elbow", 76.0, 168.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "torsoStable", "lockout")),
    Exercise(id="elevacao-lateral", name="Elevação lateral", pattern="lateralRaise", view="frontal", rep=RepRange("shoulder", 14.0, 92.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "momentum")),
    Exercise(id="elevacao-frontal", name="Elevação frontal", pattern="frontRaise", view="lateral", rep=RepRange("shoulder", 12.0, 90.0), hold=false, checks=listOf("rom", "tempo", "momentum", "torsoStable")),
    Exercise(id="crucifixo-inverso", name="Crucifixo inverso", pattern="fly", view="lateral", rep=RepRange("shoulder", 86.0, 18.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "backNeutral")),
    Exercise(id="face-pull", name="Face pull", pattern="facePull", view="frontal", rep=RepRange("elbow", 160.0, 62.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="encolhimento", name="Encolhimento", pattern="shrug", view="frontal", rep=RepRange("shrug", 8.0, 26.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="rosca-direta", name="Rosca direta", pattern="curl", view="frontal", rep=RepRange("elbow", 165.0, 46.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "momentum", "symmetry")),
    Exercise(id="rosca-alternada", name="Rosca alternada", pattern="curl", view="frontal", rep=RepRange("elbow", 166.0, 48.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "momentum")),
    Exercise(id="rosca-martelo", name="Rosca martelo", pattern="curl", view="frontal", rep=RepRange("elbow", 166.0, 50.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "symmetry")),
    Exercise(id="rosca-scott", name="Rosca scott", pattern="curl", view="lateral", rep=RepRange("elbow", 160.0, 44.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="rosca-concentrada", name="Rosca concentrada", pattern="curl", view="lateral", rep=RepRange("elbow", 162.0, 42.0), hold=false, checks=listOf("rom", "tempo")),
    Exercise(id="triceps-polia", name="Tríceps na polia", pattern="tricepsPushdown", view="lateral", rep=RepRange("elbow", 78.0, 172.0), hold=false, checks=listOf("rom", "tempo", "torsoStable", "elbowDrift")),
    Exercise(id="triceps-testa", name="Tríceps testa", pattern="tricepsExt", view="lateral", rep=RepRange("elbow", 168.0, 62.0), hold=false, checks=listOf("rom", "tempo", "elbowDrift", "symmetry")),
    Exercise(id="triceps-frances", name="Tríceps francês", pattern="tricepsExt", view="lateral", rep=RepRange("elbow", 170.0, 58.0), hold=false, checks=listOf("rom", "tempo", "elbowDrift")),
    Exercise(id="mergulho-banco", name="Mergulho no banco", pattern="dip", view="lateral", rep=RepRange("elbow", 168.0, 82.0), hold=false, checks=listOf("rom", "tempo", "shoulderDepth")),
    Exercise(id="paralelas", name="Paralelas", pattern="dip", view="lateral", rep=RepRange("elbow", 170.0, 76.0), hold=false, checks=listOf("rom", "tempo", "momentum", "shoulderDepth")),
    Exercise(id="agachamento-livre", name="Agachamento livre", pattern="squat", view="lateral", rep=RepRange("knee", 168.0, 88.0), hold=false, checks=listOf("depth", "tempo", "torsoLean", "backNeutral", "kneeValgus", "symmetry")),
    Exercise(id="agachamento-livre-corpo", name="Agachamento livre (peso corporal)", pattern="squat", view="lateral", rep=RepRange("knee", 170.0, 92.0), hold=false, checks=listOf("depth", "tempo", "torsoLean", "kneeValgus", "symmetry")),
    Exercise(id="agachamento-frontal", name="Agachamento frontal", pattern="squat", view="lateral", rep=RepRange("knee", 168.0, 84.0), hold=false, checks=listOf("depth", "tempo", "torsoLean", "backNeutral", "kneeValgus")),
    Exercise(id="leg-press", name="Leg press", pattern="legPress", view="lateral", rep=RepRange("knee", 165.0, 82.0), hold=false, checks=listOf("depth", "tempo", "symmetry", "lockout")),
    Exercise(id="cadeira-extensora", name="Cadeira extensora", pattern="legExtension", view="lateral", rep=RepRange("knee", 88.0, 172.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="afundo", name="Afundo", pattern="lunge", view="lateral", rep=RepRange("knee", 165.0, 92.0), hold=false, checks=listOf("depth", "tempo", "torsoLean", "kneeValgus")),
    Exercise(id="agachamento-bulgaro", name="Agachamento búlgaro", pattern="lunge", view="lateral", rep=RepRange("knee", 163.0, 90.0), hold=false, checks=listOf("depth", "tempo", "torsoLean", "kneeValgus")),
    Exercise(id="levantamento-terra", name="Levantamento terra", pattern="hinge", view="lateral", rep=RepRange("hip", 168.0, 92.0), hold=false, checks=listOf("rom", "tempo", "backNeutral", "hipShoot", "symmetry")),
    Exercise(id="stiff", name="Stiff", pattern="hinge", view="lateral", rep=RepRange("hip", 168.0, 98.0), hold=false, checks=listOf("rom", "tempo", "backNeutral", "kneeLock")),
    Exercise(id="mesa-flexora", name="Mesa flexora", pattern="legCurl", view="lateral", rep=RepRange("knee", 168.0, 52.0), hold=false, checks=listOf("rom", "tempo", "symmetry", "hipStable")),
    Exercise(id="bom-dia", name="Bom dia", pattern="hinge", view="lateral", rep=RepRange("hip", 170.0, 100.0), hold=false, checks=listOf("rom", "tempo", "backNeutral")),
    Exercise(id="elevacao-pelvica", name="Elevação pélvica", pattern="hipThrust", view="lateral", rep=RepRange("hip", 96.0, 172.0), hold=false, checks=listOf("rom", "tempo", "hipLockout", "backNeutral")),
    Exercise(id="ponte-glutea", name="Ponte de glúteo", pattern="gluteBridge", view="lateral", rep=RepRange("hip", 118.0, 170.0), hold=false, checks=listOf("rom", "tempo", "hipLockout")),
    Exercise(id="coice-polia", name="Coice na polia", pattern="kickback", view="lateral", rep=RepRange("hipMax", 118.0, 168.0), hold=false, checks=listOf("rom", "tempo", "backNeutral", "torsoStable")),
    Exercise(id="abducao-quadril", name="Abdução de quadril", pattern="hipAbd", view="frontal", rep=RepRange("hipAbd", 8.0, 40.0), hold=false, checks=listOf("rom", "tempo", "torsoStable")),
    Exercise(id="panturrilha-pe", name="Panturrilha em pé", pattern="calfRaise", view="lateral", rep=RepRange("ankle", 104.0, 132.0), hold=false, checks=listOf("rom", "tempo", "symmetry")),
    Exercise(id="panturrilha-sentado", name="Panturrilha sentado", pattern="calfRaise", view="lateral", rep=RepRange("ankle", 102.0, 128.0), hold=false, checks=listOf("rom", "tempo")),
    Exercise(id="abdominal-crunch", name="Abdominal crunch", pattern="crunch", view="lateral", rep=RepRange("trunk", 155.0, 122.0), hold=false, checks=listOf("rom", "tempo", "headPos")),
    Exercise(id="elevacao-pernas", name="Elevação de pernas", pattern="legRaise", view="lateral", rep=RepRange("hip", 168.0, 96.0), hold=false, checks=listOf("rom", "tempo", "backNeutral")),
    Exercise(id="prancha", name="Prancha", pattern="plank", view="lateral", rep=RepRange("hold", 0.0, 0.0), hold=true, checks=listOf("hipSag", "headPos")),
    Exercise(id="abdominal-bicicleta", name="Abdominal bicicleta", pattern="crunch", view="lateral", rep=RepRange("trunk", 152.0, 118.0), hold=false, checks=listOf("rom", "tempo", "headPos", "symmetry")),
    Exercise(id="mountain-climber", name="Mountain climber", pattern="mountain", view="lateral", rep=RepRange("hipMin", 168.0, 108.0), hold=false, checks=listOf("tempo", "hipSag", "symmetry")),
)
